#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""MAC-with-load conformance — the instruction form the STATIC voice's
interpolating resampler is built out of, and which emac-conform.py does not
reach.

The Octatrack's resampler inner loop (firmware 0x40001040) is:

    macw %a6u,%d7l,%a1@+,%fp        | multiply a6.u * d7.l into ACC0,
    macw %a0u,%d6l,%a5@-,%a0        | AND load the next coefficient into the
                                    | very register that supplied the operand

so the multiply MUST use the register's value from BEFORE the parallel load,
and the address register must write back. Everything here is computed from the
MCF54455RM's definition of MAC, never from observing an emulator.

  emac-macload.py [--asm] [--qemu PATH]
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_QEMU = ROOT / "vendor" / "qemu" / "build" / "qemu-system-m68k"
RAM_BASE = 0x40000000

PROLOGUE = r"""
| MAC-with-load conformance, generated by tests/emac-macload.py.
    .text
    .globl  _start
_start:
    move.l  #0x40800000,%sp
    lea     0xfc060000,%a1
    move.b  #0x30,%a1@(8)
    move.b  #0x20,%a1@(8)
    move.b  #0x13,%a1@(0)
    move.b  #0x07,%a1@(0)
    move.b  #0x05,%a1@(8)
"""

EPILOGUE = r"""
    halt

| ---- putc: %d6 low byte -> UART0
putc:
    lea     0xfc06000c,%a0
    move.b  %d6,%a0@
    rts
| ---- puthex8: %d2 -> eight hex digits + newline
puthex8:
    move.l  #28,%d5
ph_loop:
    move.l  %d2,%d6
    lsr.l   %d5,%d6
    and.l   #15,%d6
    add.l   #48,%d6
    cmp.l   #57,%d6
    ble     ph_emit
    add.l   #39,%d6
ph_emit:
    bsr     putc
    subq.l  #4,%d5
    bge     ph_loop
    move.l  #10,%d6
    bsr     putc
    rts
"""


def emit(name, body):
    return f"\n| ---- {name}\n{body}\n"


# MACSR: fractional off (integer mode), signed, no saturation -> plain
# integer multiply-accumulate, which is the easiest form to predict exactly.
MACSR_INT_SIGNED = 0x00000000


def gen():
    code = []

    # A coefficient table the parallel load walks.
    code.append(emit("setup", r"""
    move.l  #0x00000000,%d0
    move.l  %d0,%macsr
    move.l  #0,%acc0
    lea     coefs,%a1
    move.l  #0x00030000,%fp        | a6 upper half = 3
    move.l  #0x00000005,%d7        | d7 lower half = 5
"""))

    # ACC0 += a6.u * d7.l = 3 * 5 = 15, and a6 <- [a1], a1 += 4.
    code.append(emit("mac1", r"""
    mac.w   %a6u,%d7l,%a1@+,%fp
    move.l  %acc0,%d2
    bsr     puthex8                | expect 0000000f
    move.l  %fp,%d2
    bsr     puthex8                | expect 00070000  (coefs[0])
    move.l  %a1,%d2
    sub.l   #coefs,%d2
    bsr     puthex8                | expect 00000004  (a1 advanced)
"""))

    # Second MAC: a6.u is now 7 (loaded above), d7.l still 5 -> += 35 -> 50.
    code.append(emit("mac2", r"""
    mac.w   %a6u,%d7l,%a1@+,%fp
    move.l  %acc0,%d2
    bsr     puthex8                | expect 00000032  (15 + 35)
    move.l  %fp,%d2
    bsr     puthex8                | expect 000b0000  (coefs[1])
"""))

    # Pre-decrement form, the other half of the firmware's loop.
    code.append(emit("mac3", r"""
    move.l  #0,%acc0
    lea     coefs+8,%a5
    move.l  #0x00040000,%a0
    move.l  #0x00000006,%d6
    mac.w   %a0u,%d6l,%a5@-,%a0
    move.l  %a0,%d3                | stash: putc clobbers %a0
    move.l  %acc0,%d2
    bsr     puthex8                | expect 00000018  (4 * 6)
    move.l  %d3,%d2
    bsr     puthex8                | expect 000b0000  (coefs[1], predec)
    move.l  %a5,%d2
    sub.l   #coefs,%d2
    bsr     puthex8                | expect 00000004  (a5 decremented)
"""))

    return (PROLOGUE + "".join(code) + EPILOGUE +
            "\n    .section .rodata\n    .align 4\ncoefs:\n"
            "    .long 0x00070000\n    .long 0x000b0000\n"
            "    .long 0x000d0000\n    .long 0x00110000\n")


EXPECT = [
    ("mac1 acc0        = a6.u*d7.l = 3*5", 0x0000000F),
    ("mac1 a6 after     = coefs[0]", 0x00070000),
    ("mac1 a1 advanced  = +4", 0x00000004),
    ("mac2 acc0         = 15 + 7*5", 0x00000032),
    ("mac2 a6 after     = coefs[1]", 0x000B0000),
    ("mac3 acc0         = 4*6", 0x00000018),
    ("mac3 a0 after     = coefs[1]", 0x000B0000),
    ("mac3 a5 predec    = +4", 0x00000004),
]


def main():
    qemu = Path(sys.argv[sys.argv.index("--qemu") + 1]) if "--qemu" in sys.argv \
        else DEFAULT_QEMU
    asm = gen()
    if "--asm" in sys.argv:
        print(asm)
        return 0
    with tempfile.TemporaryDirectory() as td:
        d = Path(td)
        (d / "t.s").write_text(asm)
        ld = d / "t.ld"
        ld.write_text("SECTIONS { . = %#x; .text : { *(.text) } "
                      ".rodata : { *(.rodata) } }\n" % RAM_BASE)
        for cmd in (["m68k-elf-as", "-mcpu=54454", "-o", str(d / "t.o"),
                     str(d / "t.s")],
                    ["m68k-elf-ld", "-T", str(ld), "-o", str(d / "t.elf"),
                     str(d / "t.o")]):
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode:
                print(r.stderr, file=sys.stderr)
                return 2
        cmd = [str(qemu), "-M", "mcf5208evb", "-cpu", "cfv4e",
               "-kernel", str(d / "t.elf"),
               "-display", "none", "-monitor", "none", "-serial", "stdio",
               "-no-reboot"]
        # ColdFire `halt` stops the CPU but never exits QEMU; the timeout is
        # the termination signal, sound because every result is emitted first.
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
            out = r.stdout + r.stderr
        except subprocess.TimeoutExpired as exc:
            def dec(b):
                if b is None:
                    return ""
                return b.decode(errors="replace") if isinstance(b, bytes) else b
            out = dec(exc.stdout) + dec(exc.stderr)
    got = re.findall(r"^([0-9A-Fa-f]{8})$", out, re.M)
    print(f"MAC-with-load — the resampler's instruction form\n")
    bad = 0
    for i, (label, want) in enumerate(EXPECT):
        g = int(got[i], 16) if i < len(got) else None
        ok = g == want
        bad += not ok
        gs = f"{g:#010x}" if g is not None else "MISSING"
        print(f"  {'OK ' if ok else 'BAD'} {label:34s} want {want:#010x}  got {gs}")
    print(f"\n  {len(EXPECT)-bad} pass, {bad} fail")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
